[project]
name = "blockchainchess"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "chess>=1.11.2",
    "ecdsa>=0.19.1",
    "fastapi>=0.124.0",
]
